/home/smaity/Transfer-learning/without-label-V2/kdeClassifier.py:31: RuntimeWarning: invalid value encountered in log
  for Xi in training_sets] + np.log(weights)
/home/smaity/Transfer-learning/without-label-V2/kdeClassifier.py:31: RuntimeWarning: invalid value encountered in log
  for Xi in training_sets] + np.log(weights)
/home/smaity/Transfer-learning/without-label-V2/kdeClassifier.py:31: RuntimeWarning: invalid value encountered in log
  for Xi in training_sets] + np.log(weights)
